baseurl = "https://crypto.rogerjbos.com/"
languageCode = "en-us"
title = "Cardano [BOS] Stake Pool"
theme = "ghostwriter"
googleAnalytics = "UA-121878757-3"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
copyright = "2021 - Roger J. Bos, CFA"

[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "Roger J. Bos, CFA"
    profile = ""

[Taxonomies]
    tag = "tags"

[Params]
    mainSections = ["Home"]
    intro = true
    headline = "Cardano [BOS]Pool"
    description = "Stake Like a Boss!"
    github = "https://github.com/rogerjbos"
    gitlab = ""
    linkedin = "https://linkedin.com/in/rogerjbos/"
    twitter = "https://twitter.com/rogerjbos"
    telegram = "https://telegram/rogerbos"
    stackoverflow = "https://stackoverflow.com/users/7351478"
    email = "me@rogerjbos.com"
    opengraph = true
    shareTwitter = true
    shareTelegram = true
    shareGooglePlus = false
    shareLinkedIn = true
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    exponeaJsUrl = ""
    exponeaTarget = ""
    exponeaToken = ""
    exponeaTrackVisits = false
    readingTime = false
    readingTimeText = "Estimated reading time:"

[permalinks]
    post = "/:slug/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Staking"
    url = "/staking/"
    weight = 3
[[menu.main]]
    name = "FAQ"
    url = "/faq/"
    weight = 4

[params]
    description = "Cardano [BOS] Stake Pool"
    # <script type="text/javascript" src="https://platform.linkedin.com/badges/js/profile.js" async defer></script> 
    # <div class="LI-profile-badge"  data-version="v1" data-size="medium" data-locale="en_US" data-type="horizontal" data-theme="light" data-vanity="rogerjboscfa"><a class="LI-simple-link" href='https://www.linkedin.com/in/rogerjboscfa?trk=profile-badge'>Roger J. Bos, CFA</a></div>

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    [params.logo]
    url = "https://crypto.rogerjbos.com/cardano-ada-logo.svg"
    width = 50
    height = 50
    alt = "Logo"
